--- #YAML:1.0
name:                X11-GUITest-record
version:             0.13
abstract:            Perl implementation of the X11 record extension
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Marc Koderer <koderer@ecos.de> / ecos GmbH, Gerald Richter <richter@ecos.de> / ecos GmbH
